**What are defer, panic and recover? How do you recover from a run-time panic?**

`Defer` schedules a function call to be run after the function completes. It is often used when resources need to be freed in some way.

Example:

```go
package main

import "fmt"

func first() {
     fmt.Println("1st")
}
func second() {
     fmt.Println("2nd")
}
func main() {
     defer second()
     first()
}
```
This program prints `1st` followed by `2nd`. Basically, `defer` moves the call to `second` to the end of the function.

`Panic` is a run-time error. A run-time panic can be handled with the built-in `recover` function. `Recover` stops the panic and returns the value that was passed to the call to `panic`.

For instance:

```go
package main

import "fmt"

func main() {
     defer func() {
     	   str := recover()
	   fmt.Println(str)
     } ()
     panic("PANICKING!")
}
```
Note the `()` after `defer`, that's a function call. `defer` works with a called function only.

A panic generally indicates a programmer error (for example attempting to access an index of an array that's out of bounds, forgetting to initialize a map, etc.) or an exceptional condition that there's no easy way to recover from. (Hence the name “panic”)